steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/dev-api', './api']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/dev-api']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'dev-api',
        '--image', 'gcr.io/$PROJECT_ID/dev-api',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]